name: The Differentiation
favicon: null
layout_spectrum: 0.0815991007257253
typography_spectrum: 0
title: The Differentiation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.2208961988799274
  lightness: 0.6011940499302
  saturation: 0.3547423998825252
  rhythmicContrast: 0.061388210859149694
purpose: []
