name: The Differentiation
favicon: null
layout_spectrum: 0.25145
typography_spectrum: 0
title: The Differentiation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#fffbff'
    - '#ffd6e1'
    - '#feabb4'
    - '#955962'
  brandStrength: 0.09091786877252162
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.2862143835518509
purpose: []
