typography_spectrum: 0
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#dfdfdf'
    - '#676767'
    - '#8b8b8b'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.2862143835518509
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25145
analytics:
  google: null
  facebook: null
  twitter: null
name: The Differentiation
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Dare Be Yourself
purpose: []
