typography_spectrum: 0
color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.579901912715286
  lightness: 0.6198121653869748
  saturation: 0.3701105082873255
  rhythmicContrast: 0.10830088262446225
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4093529749661684
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: The Differentiation
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/4888b7b7-29ca-4401-809c-a2d4586a3fcb.png'
title: Dare Be Yourself
purpose: []
